apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vault
  name: vault
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vault
  serviceName: vault
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vault
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: CHECK_INTERVAL
          value: "10"
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: gcs-bucket-name
              name: vault
        - name: KMS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: kms-key-id
              name: vault
        image: gcr.io/propane-dogfish-315818/vault-init
        imagePullPolicy: Always
        name: vault-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - server
        - -config=/etc/vault/config/vault.hcl
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: VAULT_API_ADDR
          valueFrom:
            configMapKeyRef:
              key: api-addr
              name: vault
        - name: VAULT_CLUSTER_ADDR
          value: https://$(POD_IP):8201
        image: vault:1.8.2
        imagePullPolicy: IfNotPresent
        name: vault
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        - containerPort: 8201
          name: server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/sys/health?standbyok=true
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/vault/config
          name: vault-config
        - mountPath: /etc/vault/tls
          name: vault-tls
        - mountPath: /secrets/userlookup
          name: userlookup-secret
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          cat > /etc/vault/config/vault.hcl <<EOF
          default_lease_ttl = "24h"
          log_format = "json"
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_cert_file = "/etc/vault/tls/tls.crt"
            tls_key_file = "/etc/vault/tls/tls.key"
            tls_min_version = "tls12"
          }

          storage "gcs" {
            bucket = "${GCS_BUCKET_NAME}"
            ha_enabled = "true"
          }

          ui = true
          EOF
        command:
        - /bin/sh
        - -c
        env:
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: gcs-bucket-name
              name: vault
        image: busybox
        imagePullPolicy: Always
        name: config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/vault/config
          name: vault-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: vault-config
      - name: vault-tls
        secret:
          defaultMode: 420
          secretName: vault-i-tls
      - name: userlookup-secret
        secret:
          defaultMode: 420
          secretName: userlookup-svc-acct
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
